apiVersion: v1
kind: Service
metadata:
  name: simple-web-app
spec:
  type: NodePort
  selector:
    app: simple-web-app
  ports:
    - port: 80
      #targetPort is the port on which our application is running i.e. the container port
      targetPort: 80
      #the port on which our application will mapped with the kind cluster
      nodePort: 30007




